---
- name: Update apt repo/cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install i3wm
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - i3
    - i3-wm
    - i3lock
    - i3status
    - conky
