---
- name: Update apt repo/cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install tools from standard repo
  become: true
  ansible.builtin.apt:
    name: "{{ item.packages }}"
    state: present
  loop:
    - "{{ package_list }}"
  when: ansible_os_family == item.os
