---
- name: Update apt repo/cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Import package list
  ansible.builtin.include_vars: packages.yml

- name: Install tools from common
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ package_list.all_os }}"

- name: Install tools specific to debian
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ package_list[ansible_os_family] }}"
