---
- name: Update apt repo/cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Setup Docker
  block:
    - name: Uninstall built-in Docker if installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      loop:
        - docker.io
        - docker-compose
        - docker-doc
        - docker-compose
        - podman-compose
        - containerd
        - runc

    - name: Add Docker keyring to apt
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/debian/gpg"
        state: present

    - name: Install Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

    - name: Install Docker
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

- name: Install tools from standard repo
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - tmux
    - vim
    - nmap
    - firefox-esr
    - bc
    - netcat-openbsd
    - binwalk
    - bleachbit
    - curl
    - wget
    - jq
    - graphicsmagick
    - gzip
    - p7zip
    - hydra
    - keepassxc
    - make
    - ncftp
    - mplayer
    - mousepad
    - nmap
    - openvpn
    - openssh-client
    - python3
    - remmina
    - rsync
    - seahorse
    - socat
    - telnet
    - vlc
    - whois
    - wireshark
    - exiftool
    - flameshot
