---
- name: Customize OS
  become_method: sudo
  hosts: localhost
  connection: local
  roles:
    - configure-utils
    - install-tools
    - customize-browser
    - configure-logging
    - configure-system
