---
- name: Customize OS
  gather_facts: true
  become_method: sudo
  hosts: localhost
  connection: local
  roles:
    - configure-home
    - install-tools
    - customize-browser
    - configure-logging
    - configure-system
