---
- name: Clone dotfiles repo
  ansible.builtin.include_role: 
    name: download-dotfiles

- name: Check for i3 installation
  ansible.builtin.stat:
    path: $HOME/.config/i3
  register: is_i3_installed

- name: Link config files | i3
  ansible.builtin.file:
    src: $HOME/dotfiles/i3
    dest: $HOME/.config/i3
    state: link
    force: true
  when: is_i3_installed.stat.isdir is defined
