---
- name: Clone dotfiles repo
  ansible.builtin.include_role: 
    name: download-dotfiles

- name: Check for fluxbox installation
  ansible.builtin.package_facts:
    manager: auto

- name: Link config files | fluxbox
  ansible.builtin.file:
    src: $HOME/dotfiles/fluxbox
    dest: $HOME/.fluxbox
    state: link
    force: true
  when: "'fluxbox' in ansible_facts.packages"
