---
- name: Clone dotfiles repo
  ansible.builtin.include_role:
    name: download-dotfiles

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Link config files
  block:
    - name: Link config files | bashrc
      ansible.builtin.file:
        src: $HOME/dotfiles/bashrc
        dest: $HOME/.bashrc
        state: link
        force: true

    - name: Link config files | tmux.conf
      ansible.builtin.file:
        src: $HOME/dotfiles/tmux.conf
        dest: $HOME/.tmux.conf
        state: link
        force: true

    - name: Link config files | vimrc
      ansible.builtin.file:
        src: $HOME/dotfiles/vimrc
        dest: $HOME/.vimrc
        state: link
        force: true

    - name: Link config files | Xdefaults
      ansible.builtin.file:
        src: $HOME/dotfiles/Xdefaults
        dest: $HOME/.Xdefaults
        state: link
        force: true

    - name: Link config files | i3
      ansible.builtin.file:
        src: $HOME/dotfiles/i3
        dest: $HOME/.config/i3
        state: link
        force: true
      when: "'i3' in ansible_facts.packages"

    - name: Link config files | fluxbox
      ansible.builtin.file:
        src: $HOME/dotfiles/fluxbox
        dest: $HOME/.fluxbox
        state: link
        force: true
      when: "'fluxbox' in ansible_facts.packages"

    - name: Link config files | spectrwm
      ansible.builtin.file:
        src: $HOME/dotfiles/spectrwm.conf
        dest: $HOME/.spectrwm.conf
        state: link
        force: true
      when: "'spectrwm' in ansible_facts.packages"

- name: Create directory to hold custom scripts
  ansible.builtin.file:
    path: $HOME/.local/bin
    state: absent
    
- name: Install custom utils
  ansible.builtin.file:
    src: $HOME/dotfiles/local/bin
    dest: $HOME/.local/bin
    state: link
    force: true

- name: CentOS specific configs
  ansible.builtin.include_tasks: ./centos.yml
  when: ansible_distribution == "CentOS"

- name: Fedora specific configs
  ansible.builtin.include_tasks: ./fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Ubuntu specific configs
  ansible.builtin.include_tasks: ./ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Debian specific configs
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == 'Debian'
