---
- name: Clone dotfiles repo
  ansible.builtin.include_role: 
    name: roles/download-dotfiles

- name: Check for spectrwm installation
  ansible.builtin.package_facts:
    manager: auto

- name: Link config files | spectrwm
  ansible.builtin.file:
    src: $HOME/dotfiles/spectrwm.conf
    dest: $HOME/.spectrwm.conf
    state: link
    force: true
  when: "'spectrwm' in ansible_facts.packages"
