---
- name: CentOS
  ansible.builtin.include_tasks: ./centos.yml
  when: ansible_distribution == "CentOS"

- name: Fedora
  ansible.builtin.include_tasks: ./fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Ubuntu
  ansible.builtin.include_tasks: ./ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Debian
  ansible.builtin.include_tasks: ./debian.yml
  when: ansible_distribution == 'Debian'
