---
- name: Update apt repo/cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install fluxbox
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - fluxbox
